name: bloody_violence
description: A sample Polymer application
dependencies:
  core_elements: '>=0.0.6 <0.1.0'
  paper_elements: '>=0.0.1 <0.1.0'
  polymer: '>=0.11.0 <0.12.0'
  route: any
  start: any
transformers:
- polymer:
    entry_points: web/index.html
